### PR TITLE
added multiselect and add items to collection in admin

### PR DESCRIPTION
**Pull request by vipulnarang95**
## Description

Feature added:
Add items to collection action added for all moderated models in cms_config

## Related resources

* #...
* #...

## Checklist

* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst)

### CODE REVIEW

**Comment by vipulnarang95** [comment]
@fsbraun Please check and review

**Comment by fsbraun** [comment]
Looks good. Can you add some tests? What happens if there are published, unpublished or archived objects selected when the action is run?

**Comment by fsbraun** [comment]
Actually, this is a nice example of the power of `cms_config`.

**Comment by vipulnarang95** [comment]
Tests are already there: https://github.com/django-cms/djangocms-moderation/blob/master/tests/test_forms.py#L146
Do you want me to add some specific?

**Comment by fsbraun** [comment]
Test adding a mixture of objects with different version states. I would expect a user message that some items could not be added to the collection since they are not drafts, or are locked.

**Comment by vipulnarang95** [comment]
Hi @fsbraun , I was trying adding test cases accordingly but after writing initial test cases and debugging, found that add_items_to_collection only checks if version_ids are available it will return a redirect url to moderation screen.
https://github.com/django-cms/djangocms-moderation/blob/master/djangocms_moderation/admin_actions.py#L143
The else section only gets called when nothing is selected.
Can you please check once?

**Comment by vipulnarang95** [comment]
Hi @fsbraun  can you also check my comment above?

**Comment by fsbraun** [comment]
@vipulnarang95 Yes, it seems `add_items_to_collection` redirects to this view: https://github.com/django-cms/djangocms-moderation/blob/e2e8ac25bf4f9b42f6a56d2a9fb32df3fd74d94a/djangocms_moderation/views.py#L31. So, it'll be great if we could test if this view reacts if you tried to add, say, an already published object to the moderation request. (Or, maybe, that's already done somewhere else?)

**Comment by vipulnarang95** [comment]
@fsbraun Agreed but this redirects to the moderation view by just checking the versions and there is no logic in the code to check if the versions are draft/published.
It just checks if there is version of the content model or not.

**Review by fsbraun — APPROVED** [review]

**Comment by vipulnarang95** [comment]
> I'm not sure if I understand. Are you saying that you can add published versions to a moderation request? Does that make sense? I'd expect to get an error message if I tried to do this.
>  No this gets dropped from the collection as this doesn't makes any sense..
> I now looked at the code and see that the `CollectionItemForm` does just drop unsutable versions (like published versions) from the selection. (And that's covered by tests.)
Yes that is covered which I was saying

**Comment by vipulnarang95** [comment]
Also @fsbraun can you also give me the access to release these addons?

**Pull request merged**
