### PR TITLE
Fix: Treebeard support improved

### PR DESCRIPTION
**Pull request by marksweb**
This improves support in admin for treebeard by extending a treebeard template instead of overriding and copying what it does.

Fixes 240

### CODE REVIEW

**Review by fsbraun — APPROVED** [review]
Beautiful code. The best I've ever seen!

**Review by fsbraun — APPROVED** [review]
Beautiful code. The best I've ever seen!

**Review by adam-murray — APPROVED** [review]
Beautiful code, the second best I have ever seen!

**Review by fsbraun — APPROVED** [review]
Beautiful code. The best I've ever seen!

**Pull request merged**
