### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Review by NarenderRajuB — APPROVED** [review]

**Comment by vinitkumar** [comment]
@crydotsnake We will only be able to merge this when all the tests pass.

**Comment by crydotsnake** [comment]
> @crydotsnake We will only be able to merge this when all the tests pass.

I didn't found the issue yet.. 😕

**Comment by marksweb** [comment]
> @crydotsnake We will only be able to merge this when all the tests pass.

@vinitkumar I can't actually get the test suite to pass on the current `release/1.0.x` branch.

Just checking out the branch & running `tox` - almost everything fails.

**Review by Aiky30 — CHANGES_REQUESTED** [review]
This project is not ready for the "standard" test settings that have been created. It doesn't use Django CMS 3 and it requires versioning. The versioning tests have been broken. This package will need to be patched by one of the v4 developers as it has a very different setup.

**Comment by crydotsnake** [comment]
> This project is not ready for the "standard" test settings that have been created. It doesn't use Django CMS 3 and it requires versioning. The versioning tests have been broken. This package will need to be patched by one of the v4 developers as it has a very different setup.

Okay. Thanks for your comment Andrew!

**Pull request closed without merging**
