### PR TITLE
Added data-popup attr to a tag

### PR DESCRIPTION
**Pull request by vipulnarang95**
## Description
Added an attribute from parent a tag to be included in burger menu item.

Attribute name: data-popup

Data popup is needed to open a link in burger menu in another window. this value is present in the original html of the link but not included while creating the burger menu.
for your reference: https://github.com/FidelityInternational/djangocms-content-expiry/blob/main/djangocms_content_expiry/templates/djangocms_content_expiry/calendar_icon.html

## Related resources

* #...
* #...

## Checklist

* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst)

## Summary by Sourcery

New Features:
- Add support for 'data-popup' attribute in burger menu items.

### CODE REVIEW

**Comment by vipulnarang95** [comment]
Hi @fsbraun @Aiky30 ,
Can you please help review this?

Thanks
Vipul

**Review by fsbraun — APPROVED** [review]
LGTM!

**Comment by fsbraun** [comment]
@vipulnarang95 Any idea why the coverage is dropping?

**Comment by vipulnarang95** [comment]
@fsbraun I am not sure. I guess code coverage is the same as per other PR's. As you can see just added 3 lines of code.

**Comment by fsbraun** [comment]
@vipulnarang95 Yes, of course. That's strange, though. Must be a some other effect. I just don't know what.

**Pull request merged**
